sudo: required
language: php
services:
    - postgresql
addons:
    postgresql: '11.2'
php:
#    - '7.1'
#    - '7.2'
    - '7.3'

env:
    - POSTGRES_NAME=project
    - POSTGRES_PORT=5432
    - POSTGRES_HOST=localhost
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=

before_install:
    - psql -f /docker-entrypoint-initdb.d/init.sql -U postgres

before_script:
    - composer install

script:
    - vendor/bin/phpunit --color -c phpunit.xml.dist

after_success:
    - travis_retry vendor/bin/php-coveralls