sudo: required
language: php
services:
    - postgresql
addons:
    postgresql: '11.2'
php:
#    - '7.1'
#    - '7.2'
    - '7.3'

env:
    - POSTGRES_NAME=project POSTGRES_PORT=5432 POSTGRES_HOST=localhost POSTGRES_USER=postgres POSTGRES_PASSWORD= PGPORT=5432

before_install:
    - sudo apt-get update
    - sudo apt-get --yes remove postgresql\*
    - sudo apt-get install -y postgresql-11 postgresql-client-11
    - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
    - sudo service postgresql restart 11
    - psql -f ./tests/init.sql -U postgres -p 5432
    - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

before_script:
    - composer install

script:
    - vendor/bin/phpunit --color -c phpunit.xml.dist

after_success:
    - travis_retry vendor/bin/php-coveralls